[pytest]
DJANGO_SETTINGS_MODULE = baseapi.settings
python_files = tests.py test_*.py *_tests.py
addopts = -m "not integration"
filterwarnings =
    ignore::DeprecationWarning:environ
markers =
    integration: tests that hit real external APIs/websites
