# Generated by Django 4.2.28 on 2026-02-06 14:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserTopicSecret",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(max_length=128, primary_key=True, serialize=False)),
                ("topic_secret", models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                "db_table": "user_topic_secrets",
            },
        ),
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(db_index=True, max_length=128)),
                ("fcm_token", models.TextField(unique=True)),
                ("device_type", models.CharField(choices=[("ios", "iOS"), ("android", "Android")], max_length=20)),
                ("device_name", models.CharField(blank=True, max_length=100, null=True)),
                ("device_id", models.CharField(max_length=255)),
                ("app_version", models.CharField(blank=True, max_length=20, null=True)),
                ("os_version", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "language",
                    models.CharField(choices=[("nl", "Nederlands"), ("en", "English")], default="nl", max_length=10),
                ),
            ],
            options={
                "db_table": "user_devices",
                "indexes": [models.Index(fields=["user_id", "language"], name="idx_user_device_user_lang")],
                "unique_together": {("user_id", "device_id")},
            },
        ),
    ]
