- name: Deploy KortingKlok Backend
  become: true
  hosts: all
  tasks:
    - name: Create configuration directory
      file:
        path: /etc/kortingklok
        state: directory

    - name: Create certbot webroot directory
      file:
        path: /var/www/certbot
        state: directory

    - name: Install certbot
      apt:
        name: certbot
        state: present
        update_cache: yes

    - name: Obtain SSL certificate
      shell: |
        certbot certonly \
          --standalone \
          -d api.kortingklok.nl \
          --non-interactive \
          --agree-tos \
          --keep-until-expiring \
          --email hallo@kortingklok.nl

    - name: Copy docker image to host
      copy:
        src: "{{ docker_image_path }}"
        dest: /etc/kortingklok/docker-image.tar

    - name: Load docker image from .tar file
      shell: |
        docker load < /etc/kortingklok/docker-image.tar

    - name: Delete docker image .tar file
      file:
        path: /etc/kortingklok/docker-image.tar
        state: absent

    - name: Copy docker-compose file
      template:
        src: tmpls/docker-compose.yml.j2
        dest: /etc/kortingklok/docker-compose.yml

    - name: Copy nginx config
      copy:
        src: tmpls/nginx.conf
        dest: /etc/kortingklok/nginx.conf

    - name: Copy firebase-adminsdk.json
      copy:
        src: "{{ firebase_adminsdk_json_path }}"
        dest: /etc/kortingklok/firebase-adminsdk.json

    - name: docker-compose up -d
      shell: |
        docker compose -f /etc/kortingklok/docker-compose.yml up -d

    - name: Set up certbot auto-renewal cron
      cron:
        name: "Certbot renewal"
        minute: "30"
        hour: "3"
        job: "certbot renew --quiet --pre-hook 'docker stop kortingklok_nginx' --post-hook 'docker start kortingklok_nginx'"

    - name: Set up scraper cron
      cron:
        name: "Scrape all supermarkets"
        minute: "0"
        hour: "*/6"
        job: "docker exec kortingklok_worker make scrape-all-supermarkets"

    - name: Remove unused docker images
      shell: |
        docker image prune -a -f
