# Generated by Django 4.2.28 on 2026-02-14 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("external_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        related_query_name="child",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="Supermarket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
                ("logo_url", models.TextField(blank=True, null=True)),
                ("website_url", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "supermarkets",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("external_id", models.CharField(max_length=100)),
                ("image_url", models.TextField(blank=True, null=True)),
                ("website_url", models.TextField(blank=True, null=True)),
                ("base_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("current_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("has_discount", models.BooleanField(default=False)),
                ("discount_text", models.TextField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        related_query_name="product",
                        to="products.category",
                    ),
                ),
                (
                    "supermarket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        related_query_name="product",
                        to="products.supermarket",
                    ),
                ),
            ],
            options={
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("base_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("has_discount", models.BooleanField(default=False)),
                ("discount_text", models.TextField(blank=True, null=True)),
                ("run_id", models.UUIDField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_histories",
                        related_query_name="price_history",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "price_history",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="supermarket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                related_query_name="category",
                to="products.supermarket",
            ),
        ),
        migrations.CreateModel(
            name="UserTrackedProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(max_length=128)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_by",
                        related_query_name="tracked_product",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "user_tracked_products",
                "unique_together": {("user_id", "product")},
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["supermarket", "is_available"], name="idx_product_supermarket_avail"),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("supermarket", "external_id")},
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(fields=["run_id", "product"], name="idx_price_history_run_product"),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("supermarket", "external_id")},
        ),
    ]
