# Generated by Django 4.2.28 on 2026-02-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category", "is_available"], name="idx_product_category_avail"),
        ),
    ]
