name: Backend Build

on:
  push:
    branches: [master]
    paths:
      - "deploy/**"
      - "backend/**"
      - ".github/workflows/backend.yml"
  pull_request:
    branches: [master]
    paths:
      - "deploy/**"
      - "backend/**"
      - ".github/workflows/backend.yml"
  schedule:
    - cron: "0 12 * * *"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: bash install_python_packages.sh

      - name: Lint
        run: make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_USER: baseapi
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: baseapi
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:8-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: bash install_python_packages.sh

      - name: Run migrations
        run: make db-migrate

      - name: Run tests
        run: make test

  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/master' && github.event_name != 'schedule'
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Build
        uses: docker/build-push-action@v6
        with:
          context: backend
          file: backend/Dockerfile
          push: false
          tags: kortingklok:${{ github.sha }}
      
      - name: Docker Save
        run: docker save kortingklok:${{ github.sha }} > /tmp/docker-image.tar

      - name: Write Firebase Service Account JSON
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > /tmp/firebase-adminsdk.json

      - name: Run Playbook
        uses: dawidd6/action-ansible-playbook@v7
        with:
          directory: deploy
          playbook: main.yaml
          configuration: |
            [defaults]
            inventory = inventory.yaml
            host_key_checking = False
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # https://docs.docker.com/engine/install/ubuntu/
          inventory: |
            [all]
            46.224.142.215 ansible_user=root
          options: |
            -e "docker_image_tag=${{ github.sha }}"
            -e "docker_image_path=/tmp/docker-image.tar"
            -e "django_secret_key=${{ secrets.DJANGO_SECRET_KEY }}"
            -e "postgresql_password=${{ secrets.POSTGRESQL_PASSWORD }}"
            -e "firebase_adminsdk_json_path=/tmp/firebase-adminsdk.json"
